# Generated by Django 5.1.1 on 2024-10-17 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ayush', '0002_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
