# Generated by Django 5.1.1 on 2024-10-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ayush', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
